2_3: 2_3.c lib/simlib.c
	$(CC) 2_3.c lib/simlib.c -o 2_3 -lm

2_6: 2_6.c lib/simlib.c
	$(CC) 2_6.c lib/simlib.c -o 2_6 -lm

template: template.c lib/simlib.c
	$(CC) template.c lib/simlib.c -o template -lm